l_braz_por:
pm_government_run_building_steel_industry: "Construção da indústria siderúrgica operada pelo governo"
pm_government_run_building_motor_industries: "Construção das indústrias de motores operada pelo governo"
pm_government_run_building_munition_plants: "Construção de fábricas de munições operada pelo governo"
pmg_ownership_capital_building_steel_mills: "Propriedade pública"
pmg_ownership_capital_building_motor_industry: "Propriedade pública"
